version: '2'
services:
  mongodb:
    image: mongo
    container_name: docker_mongo
    ports:
      - 28017

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb

  client:
    build: .
    links:
      - mongodb
    ports:
      - 9000
    environment:
      - MONGO_URI=mongodb://mongodb/articles